### ISSUE TITLE
Class "kurl" not found

### ISSUE THREAD

**Issue by lukehatfield** [davemackintosh/kirby-twitter-plugin#1]
Hi Dave,

Thanks for the plugin. I need to display the latest tweet on a website. I can't find the kurl class though. Do I need another file to go with this?

Thanks again,
Luke

**Comment by davemackintosh** [comment]
Hey there,

I don't really recommend using the plugins since they were last updated a couple of years ago but the file you're looking for is here https://github.com/davemackintosh/kirby-curl-plugin/blob/master/curl.php.

I'm sure Kirby has much better support for this kind of thing now and the APIs it contains are probably incompatible with these.

Let me know though :)

**Comment by lukehatfield** [comment]
Thanks Dave! I didn't check the date, but that makes sense as Twitter is now requiring OAuth for a connection. I haven't asked about any more native Kirby support, but I I'm having success so far using this to help interface with Twitter: https://github.com/jublonet/codebird-php. Twitter recommended using one of the libraries from their "semi-approved" list for proper OAuth connection, etc.

**Comment by davemackintosh** [comment]
Glad you found something else, I'll mark the repos as deprecated for future :)
